DIRINFO_PLUGIN_ADDRESS equ 49152
DIRINFO_WORK_ADDRESS   equ 57344
DIRINFO_PLUGIN_SIZE    equ 4096

DIRINFO_ABI            equ 1

DIRINFOCTX_ABI         equ 0
DIRINFOCTX_SRC_PATH    equ 1
DIRINFOCTX_NAME        equ 3
DIRINFOCTX_RESULT      equ 5
DIRINFOCTX_ERROR       equ 6
DIRINFOCTX_STAGE       equ 7
DIRINFOCTX_ITEMS_LO    equ 8
DIRINFOCTX_ITEMS_HI    equ 10
DIRINFOCTX_SIZE_LO     equ 12
DIRINFOCTX_SIZE_HI     equ 14
DIRINFOCTX_SERVICES    equ 16
DIRINFOCTX_SIZE        equ 18

DIRINFO_SERVICE_PRINT  equ 0
