SYSCOPY_PLUGIN_ADDRESS equ 49152
SYSCOPY_WORK_ADDRESS   equ 57344
SYSCOPY_PLUGIN_SIZE    equ 8192

SYSCOPY_ABI            equ 1

SYSCOPYCTX_ABI         equ 0
SYSCOPYCTX_MODE        equ 1
SYSCOPYCTX_SRC_PATH    equ 2
SYSCOPYCTX_DST_PATH    equ 4
SYSCOPYCTX_NAME        equ 6
SYSCOPYCTX_RESULT      equ 8
SYSCOPYCTX_ERROR       equ 9
SYSCOPYCTX_FILES_LO    equ 10
SYSCOPYCTX_FILES_HI    equ 12
SYSCOPYCTX_DIRS_LO     equ 14
SYSCOPYCTX_DIRS_HI     equ 16
SYSCOPYCTX_SERVICES    equ 18
SYSCOPYCTX_LFN_NAME    equ 20
SYSCOPYCTX_STAGE       equ 22
SYSCOPYCTX_SIZE        equ 23

SYSCOPY_SERVICE_PRINT  equ 0
SYSCOPY_SERVICE_CANCEL equ 2
SYSCOPY_SERVICE_OVERWRITE equ 4
